import { Stock } from "../types"

export const stocks: Stock[] = [
  { id: 1, name: "NVIDIA Corporation", shortName: "NVDA", price: 26.24, logo: "/assets/stocks/nvidia.png", description:"The NVIDIA Corporation is an American multinational technology company incorporated in Delaware and based in Santa Clara, California. It is a software and fabless company which designs graphics processing units (GPUs), application programming interface (APIs) for data science and high-performance computing as well as system on a chip units (SoCs) for the mobile computing and automotive market. " },
  { id: 2, name: "Apple Inc.", shortName: "AAPL", price: 1132.13, logo: "/assets/stocks/apple.png", description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, United States. Apple is the largest technology company by revenue and, as of June 2022, is the world's biggest company by market capitalization, the fourth-largest personal computer vendor by unit sales and second-largest mobile phone manufacturer." },
  { id: 3, name: "Microsoft Corporation", shortName: "MSFT", price: 245.12, logo: "/assets/stocks/microsoft.png", description: "Microsoft Corporation is an American multinational technology corporation producing computer software, consumer electronics, personal computers, and related services headquartered at the Microsoft Redmond campus located in Redmond, Washington, United States. Its best-known software products are the Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers." },
  { id: 4, name: "Amazon.com, Inc", shortName: "AMZN", price: 88.24, logo: "/assets/stocks/amazon.png", description: `Amazon.com, Inc. is an American multinational technology company focusing on e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence. It has been referred to as "one of the most influential economic and cultural forces in the world", and is one of the world's most valuable brands. It is one of the Big Five American information technology companies, alongside Alphabet, Apple, Meta, and Microsoft.` },
  { id: 5, name: "Facebook", shortName: "FB-USD", price: 114.12, logo: "/assets/stocks/facebook.png", description: "Facebook is an online social media and social networking service owned by American company Meta Platforms. As of July 2022, Facebook claimed 2.93 billion monthly active users, and ranked third worldwide among the most visited websites as of July 2022. It was the most downloaded mobile app of the 2010s." },
  { id: 6, name: "Tesla Inc.", shortName: "TSLA", price: 179.82, logo: "/assets/stocks/tesla.png", description: "Tesla, Inc. is an American multinational automotive and clean energy company headquartered in Austin, Texas. Tesla designs and manufactures electric vehicles (electric cars and trucks), battery energy storage from home to grid-scale, solar panels and solar roof tiles, and related products and services. Tesla is one of the world's most valuable companies and remains the world's most valuable automaker with a market capitalization of more than US$550 billion." },
  { id: 7, name: "Alphabet Inc.", shortName: "GOOG", price: 96.86, logo: "/assets/stocks/alphabet.png", description: "Alphabet Inc. is an American multinational technology conglomerate holding company headquartered in Mountain View, California. It was created through a restructuring of Google on October 2, 2015, and became the parent company of Google and several former Google subsidiaries. Alphabet is the world's third-largest technology company by revenue and one of the world's most valuable companies." },
  { id: 8, name: "Intel Corporation", shortName: "INTC", price: 28.6, logo: "/assets/stocks/intel.png", description: "Intel Corporation is an American multinational corporation and technology company headquartered in Santa Clara, California. It is the world's largest semiconductor chip manufacturer by revenue, and is one of the developers of the x86 series of instruction sets, the instruction sets found in most personal computers (PCs). Incorporated in Delaware, Intel ranked No. 45 in the 2020 Fortune 500 list of the largest United States corporations by total revenue for nearly a decade, from 2007 to 2016 fiscal years." },
  { id: 9, name: "Netflix Inc.", shortName: "NFLX", price: 305.56, logo: "/assets/stocks/netflix.png", description: "Netflix, Inc. is an American subscription video on-demand over-the-top streaming service and production company based in Los Gatos, California. As of September 2022, Netflix had 222 million subscribers worldwide, including 73.3 million in the United States and Canada; 73.0 million in Europe, the Middle East and Africa, 39.6 million in Latin America and 34.8 million in the Asia-Pacific region." },
  { id: 10, name: "Adobe Inc.", shortName: "ADBE", price: 335.15, logo: "/assets/stocks/adobe.png", description: "Adobe Inc., originally called Adobe Systems Incorporated, is an American multinational computer software company incorporated in Delaware and headquartered in San Jose, California. It has historically specialized in software for the creation and publication of a wide range of content, including graphics, photography, illustration, animation, multimedia/video, motion pictures, and print." },
  { id: 11, name: "Paypal Holdings Inc.", shortName: "PYPL", price: 72.23, logo: "/assets/stocks/paypal.png", description: "PayPal Holdings, Inc. is an American multinational financial technology company operating an online payments system in the majority of countries that support online money transfers, and serves as an electronic alternative to traditional paper methods such as checks and money orders. The company operates as a payment processor for online vendors, auction sites and many other commercial users, for which it charges a fee." },
  { id: 12, name: "Visa Inc.", shortName: "V", price: 209.74, logo: "/assets/stocks/visa.png", description: "Visa Inc. is an American multinational financial services corporation headquartered in San Francisco, California. It facilitates electronic funds transfers throughout the world, most commonly through Visa-branded credit cards, debit cards and prepaid cards. Visa is one of the world's most valuable companies." },
  { id: 13, name: "Mastercard Incorporated", shortName: "MA", price: 347.23, logo: "/assets/stocks/mastercard.png", description: "Mastercard Inc. is the second-largest payment-processing corporation worldwide. It offers a range of financial services. Its headquarters are in Purchase, New York. Throughout the world, its principal business is to process payments between the banks of merchants and the card-issuing banks or credit unions of the purchasers who use the Mastercard-brand debit, credit and prepaid cards to make purchases. Mastercard has been publicly traded since 2006." },
  { id: 14, name: "Cisco System Inc.", shortName: "CSCO", price: 48.59, logo: "/assets/stocks/cisco.png", description: "Cisco Systems, Inc., commonly known as Cisco, is an American-based multinational digital communications technology conglomerate corporation headquartered in San Jose, California. Cisco develops, manufactures, and sells networking hardware, software, telecommunications equipment and other high-technology services and products. Cisco specializes in specific tech markets, such as the Internet of Things (IoT), domain security, videoconferencing, and energy management with leading products including Webex, OpenDNS, Jabber, Duo Security, and Jasper. " },
  { id: 15, name: "Oracle Corporation", shortName: "ORCL", price: 78.91, logo: "/assets/stocks/oracle.png", description: "Oracle Corporation is an American multinational computer technology corporation headquartered in Austin, Texas. The company sells database software and technology (particularly its own brands), cloud engineered systems, and enterprise software products, such as enterprise resource planning (ERP) software, human capital management (HCM) software, customer relationship management (CRM) software (also known as customer experience), enterprise performance management (EPM) software, and supply chain management (SCM) software." },
  { id: 16, name: "International Business Machines Corporation", shortName: "IBM", price: 147.5, logo: "/assets/stocks/ibm.png", description: "The International Business Machines Corporation (IBM) is an American multinational technology corporation headquartered in Armonk, New York, with operations in over 171 countries. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2021) for 29 consecutive years." },
  { id: 17, name: "Advanced Micro Devices, Inc.", shortName: "AMD", price: 70.27, logo: "/assets/stocks/amd.png", description: "Advanced Micro Devices, Inc. (AMD) is an American multinational semiconductor company based in Santa Clara, California, that develops computer processors and related technologies for business and consumer markets. AMD's main products include microprocessors, motherboard chipsets, embedded processors, graphics processors, and FPGAs for servers, workstations, personal computers, and embedded system applications." },
  { id: 18, name: "QUALCOMM Incorporated", shortName: "QCOM", price: 119.78, logo: "/assets/stocks/qualcomm.png", description: "Qualcomm is an American multinational corporation headquartered in San Diego, California, and incorporated in Delaware. It creates semiconductors, software, and services related to wireless technology. It owns patents critical to the 5G, 4G, CDMA2000, TD-SCDMA and WCDMA mobile communications standards. Over the years, Qualcomm has expanded into selling semiconductor products in a predominantly fabless manufacturing model. It also developed semiconductor components or software for vehicles, watches, laptops, wi-fi, smartphones, and other devices." },
  { id: 19, name: "Nokia Oyj", shortName: "NOK", price: 4.87, logo: "/assets/stocks/nokia.png", description: "Nokia Corporation (natively Nokia Oyj, referred to as Nokia) is a Finnish multinational telecommunications, information technology, and consumer electronics corporation, established in 1865. Nokia's main headquarters are in Espoo, Finland, in the greater Helsinki metropolitan area, but the company's actual roots are in the Tampere region of Pirkanmaa. It is the world's 415th-largest company measured by 2016 revenues according to the Fortune Global 500, having peaked at 85th place in 2009." },
  { id: 20, name: "Broadcom Inc.", shortName: "AVGO", price: 525.82, logo: "/assets/stocks/broadcom.png", description: "Broadcom Inc. is an American designer, developer, manufacturer and global supplier of a wide range of semiconductor and infrastructure software products. Broadcom's product offerings serve the data center, networking, software, broadband, wireless, and storage and industrial markets. Broadcom has a long history of corporate transactions (or attempted transactions) with other prominent corporations mainly in the high-technology space." }
]
